### ISSUE TITLE
Certificate verification results in "x509: certificate signed by unknown authority" error

### ISSUE THREAD

**Issue by lwalen** [robbiet480/go.sns#8]
I have a project that receives SNS messages and verifies them using this library. When I updated this library to the latest version (which incorporates https://github.com/robbiet480/go.sns/pull/7), payload verification started failing with the following error:
> x509: certificate signed by unknown authority

I haven't looked into the certificate itself, but is AWS not signing these via a valid authority? Or is it something on my end?

Thanks!

**Comment by KillerX** [comment]
I have the same issue. The workaround for me currently is to lock to the older version.

As a permanent I propose to roll back #7. Here is my reasoning:

* AWS seems to return just the end certificate, missing the intermediary - Causing the error above
  *  This means that in order to validate the certificate correctly the chain would have to be built manually or the intermediate certificate must be trusted by the system - Lots of hassle 
* With  #2 and #4 we are already validating that the cert is "by AWS"

Thus the check introduced by #7 is IMO not worth the trouble, and does not provide any significant improvement in security.

**Comment by robbiet480** [comment]
Reverted, thanks for investigating this one
